# Generated by Django 2.2.14 on 2020-07-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_education', models.CharField(max_length=100)),
                ('start_date_of_education', models.DateField(blank=True, null=True)),
                ('end_date_of_education', models.DateField(blank=True, null=True)),
                ('details_of_education', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_honor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalHobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_hobby', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguageSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language_skill', models.CharField(max_length=100)),
                ('programming_language_skill_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project_experience', models.CharField(max_length=100)),
                ('project_job_title', models.CharField(max_length=100)),
                ('start_date_of_project_experience', models.DateField(blank=True, null=True)),
                ('end_date_of_project_experience', models.DateField(blank=True, null=True)),
                ('details_of_project_experience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_work_and_internship', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('start_date_of_work_and_internship', models.DateField(blank=True, null=True)),
                ('end_date_of_work_and_internship', models.DateField(blank=True, null=True)),
                ('details_of_work_and_internship', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('abstract', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('text_rich', models.TextField(blank=True)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
            options={
                'ordering': ['-created_date', 'title'],
            },
        ),
    ]
