# Generated by Django 2.2.14 on 2020-08-03 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguageskill',
            name='programming_language_skill_details_rich',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
