# Generated by Django 2.2.14 on 2020-08-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_programminglanguageskill_programming_language_skill_details_rich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguageskill',
            name='programming_language_skill_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programminglanguageskill',
            name='programming_language_skill_details_rich',
            field=models.TextField(blank=True),
        ),
    ]
